### ISSUE TITLE
user-defined conversion from "Type" to "std::function<void ()>" exists

### ISSUE THREAD

**Issue by Cyken-Zeraux** [mhogomchungu/tasks#4] opened 2017-05-05 21:53 UTC
In Visual Studio 2015 Update 3, the example for using Task::run and 'then' produces the error:
`no suitable user-defined conversion from "Type" to "std::function<void ()>" exists`

```cpp
Task::run<QString>([]() {
	return QString("hi");
}).then([](QString r) {

});
```

http://i.imgur.com/9QRgDtP.png

**Comment by mhogomchungu** [comment] 2017-05-06 05:57
I only test using g++ and clang++ and that code works fine.

There are these two[1][2] methods and your compiler seems to only see the second one. Try to delete the second function and see if it will make a difference.

[1] https://github.com/mhogomchungu/tasks/blob/2fd7d2fca16e909417deec18555a2b7aa3849f27/task.h#L139
[2] https://github.com/mhogomchungu/tasks/blob/2fd7d2fca16e909417deec18555a2b7aa3849f27/task.h#L147

**Comment by mhogomchungu** [comment] 2017-11-12 17:03
I made some changes to the library and the problem you reported maybe fixed by them, can you try code below and see if the problem is still there

```
Task::run([]() {
	return QString("hi");
}).then([](QString r) {

});
```

**Closed** 2018-01-20 08:41 UTC
Labels: help wanted

**Comment by mhogomchungu** [comment] 2018-07-31 18:14
Finally got around to test this project and everything works as expected in visual studio 2017.
