### ISSUE TITLE
infinite recursion

### ISSUE THREAD

**Issue by bingcaihuang** [mhogomchungu/tasks#5] opened 2018-07-18 00:51 UTC
Hi,

When I creating a future that combines multiple functions like this:

```
auto bb = [](){	
qDebug() << "run bb";
return 6 ; } ;

Task::run( bb,bb );
```

I found that the function call has an infinite recursion.

```
	template< typename ... T >
	Task::future< void >& run( std::function< void() >f,T ... t )
	{
		auto& e = _private_future< void >() ;

		_private_add_task( e,std::move( f ),std::move( t ) ... ) ;

		return e ;
	}
```

```
	template< typename ... T >
	void _private_add_task( Task::future< void >& f,std::function< void() >&& e,T&& ... t )
	{
		_private_add_void( f,Task::run( std::move( e ) ),std::function< void() >( [](){} ) ) ;

		_private_add_task( f,std::move( t ) ... ) ;
	}
```

Task::run( std::move( e ) ) will call

```
Task::future< void >& run( std::function< void() >f,T ... t )
```
and Task::future< void >& run( std::function< void() >f,T ... t ) will call

```
_private_add_task
```
So circulate

My development environment is win7+VS2015

**Comment by mhogomchungu** [comment] 2018-07-18 06:09
Works fine here with gcc 7.3.0 and things worked the last time i tested with clang

This[1] function and a few that follows it that take a single argument of type ```Task::future< T >&``` are supposed to terminate the recursive loops. The one i linked to is the one that is supposed to kick in to terminate the loop in your particular code sample.

How large of a download is VS community edition? I have so far resisted installing it preventing me from testing the library on visual studio because bandwidth is a bit expensive where i live and all my searches have failed to give me an answer. 

[1] https://github.com/mhogomchungu/tasks/blob/daeb2446641e87528dbffc265a52e05f382529dd/task.hpp#L625

**Comment by mhogomchungu** [comment] 2018-07-18 06:15
The call chain i see here is as follows:

```
Task::future< void >& run( std::function< void() >f,T ... t )
void _private_add_task( Task::future< void >& f,std::function< void() >&& e,T&& ... t )
void _private_add_task( Task::future< void >& f,std::function< void() >&& e,T&& ... t )
void _private_add_task( Task::future< T >& f )

```

**Comment by mhogomchungu** [comment] 2018-07-18 07:01
Your code is not doing anything because you are not using the future, try below code and see if "run cc" will be printed.
```
auto bb = [](){	
qDebug() << "run bb";
return 6 ; } ;

auto cc = [](){	
qDebug() << "run cc"; } ;

Task::run( bb,bb ).queue(cc);
```

**Comment by bingcaihuang** [comment] 2018-07-18 08:00
visual_studio_community_2015 about 4Gb

I run this code：
```
auto bb = [](){	
qDebug() << "run bb";
return 6 ; } ;

auto cc = [](){	
qDebug() << "run cc"; } ;

Task::run( bb,bb ).queue(cc);
```

The result is the same, crash

**Comment by bingcaihuang** [comment] 2018-07-18 08:02
By the way, where are come from?Why the broadband cost is so expensive？I come from China

**Comment by bingcaihuang** [comment] 2018-07-18 08:06
When I run this：
```
auto bb = [](){	
qDebug() << "run bb";
return 6 ; } ;

Task::run( bb,bb );
```

The call chain i see here is as follows:
Task::run( bb,bb).get() ;
Task::future< void >& run( std::function< void() >f,T ... t )
_private_add_task( e,std::move( f ),std::move( t ) ... ) ;
_private_add_void( e,Task::run( std::move( f ) ),std::function< void() >( [](){} ) ) ;
Task::future< void >& run( std::function< void() >f,T ... t )

I infer that the problem is here：
Task::run( std::move( f ) )

**Comment by mhogomchungu** [comment] 2018-07-18 10:50
I am in Tanzania and its somewhere on the eastern part of Africa.

Internet here is expensive by local standard largely because people dont have money and internet is seen as an expensive luxury very competitive by international standards.

They sell internet here by "bundles" and they offer hourly bundles,daily bundles,weekly bundles,monthly bundles and overnight bundles.

I currently buy a weekly bundle and it costs 3000 Tanzania shillings and i get 500MB. 3000 Tanzania shillings is about 1.32 US Dollars and about 8.84 Chinese Yuan.

To download this visual studio, i will have to buy a night bundle that give me 4GB of data and it starts at 11 pm and ends at 5AM and it costs 2000 shillings(5.90 Chinese Yuan). To make sure the download will not cut off if it goes beyong 4GB,i will also have to buy a one day bundle of about 1GB just to be safe.

Suffice to say, downloading this visual studio will require spending extra money, a bit of planning and staying up late at night babysitting the download because sometimes the internet cuts off for a few seconds causing the download to stall requiring pausing it and resuming it for it to continue.

Back to the issue, visual studio seems to be taking a different path compared to clang and gcc. Will test this after i have download visual studio.

**Comment by bingcaihuang** [comment] 2018-07-18 11:10
Sorry, I didn't anticipate your network situation over there.Maybe i can try to find the problem first. My inference is that, compare with GCC, visual studio's compiler does not work in the same way.

**Comment by mhogomchungu** [comment] 2018-07-25 19:43
I can reproduce the issue with visual studio community 2017.

**Comment by bingcaihuang** [comment] 2018-07-26 16:36
Do you have any solution？

**Comment by mhogomchungu** [comment] 2018-07-31 18:13
All my tests pass on visual studio 2017 and i am closing this one as fixed.

Please reopen if you test and find the problem is still around.

**Closed by mhogomchungu** 2018-07-31 18:13 UTC

**Comment by bingcaihuang** [comment] 2018-08-09 15:42
I run the test cases on VS2015, and passed the test.

**Comment by mhogomchungu** [comment] 2018-08-09 16:14
Thanks for confirming that it works in VS2015.

The problem was caused by these two[1][2] functions. clang and gcc were picking up the first function and things worked as i expected and VS was picking up the second functiona and things break.

The solution i went with is adding this[3] private method that removes the ambiguity causing the loop to terminate correctly.

[1] https://github.com/mhogomchungu/tasks/blob/98728fbd14e68328b1744de30d2217f4cf8b8105/task.hpp#L595
[2] https://github.com/mhogomchungu/tasks/blob/98728fbd14e68328b1744de30d2217f4cf8b8105/task.hpp#L698
[3] https://github.com/mhogomchungu/tasks/blob/98728fbd14e68328b1744de30d2217f4cf8b8105/task.hpp#L612

**Comment by mhogomchungu** [comment] 2018-08-14 06:50
New version is out and it has a fix for this bug

https://github.com/mhogomchungu/tasks/releases/tag/1.2.6
